language: node_js
node_js:
  - "8"
jobs:
  include:
    - stage: functions
      before_script:
        - cd functions/catly/server
      script:
        - echo 'function!!'
        - echo 'Installing Deps!'
        - npm testing
